import 'dart:developer';
import 'dart:io';
import 'dart:isolate';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
// For Icons
import '../../../features/habit_tracker/domain/entities/habit_entity.dart';

class ImportService {
  static Future<List<HabitEntity>?> importHabitsFromCSV() async {
    // 1. Open Native File Browser (Only allow CSVs)
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );

    // User canceled the picker
    if (result == null || result.files.single.path == null) {
      return null;
    }

    // Isolate.run() automatically spins up a background thread, waits for it
    // to finish, hands the data back, and safely kills the thread.
    return await Isolate.run(
      () => _parseCSVInBackground(result.files.single.path!),
    );
  }

  /// EVERYTHING inside this function runs on a separate CPU core.
  /// It cannot talk to the UI, Riverpod, or any global variables.
  static Future<List<HabitEntity>> _parseCSVInBackground(
    String filePath,
  ) async {
    // A. Read the heavy file from disk
    final file = File(filePath);
    final String csvString = await file.readAsString();

    // B. Parse the CSV string (This is the heavy CPU math that causes freezing)
    List<List<dynamic>> csvTable = const CsvToListConverter().convert(
      csvString,
    );

    List<HabitEntity> importedHabits = [];

    // C. Convert CSV rows into Habit Entities
    for (int i = 1; i < csvTable.length; i++) {
      final row = csvTable[i];

      try {
        // Map the row columns back into a HabitEntity.
        importedHabits.add(
          HabitEntity(
            id: row[6].toString(),                // [6] is sys_id
            title: row[0].toString(),             // [0] is Habit Title
            iconCode: int.parse(row[7].toString()), // [7] is sys_icon
            colorValue: int.parse(row[8].toString()), // [8] is sys_color
            frequency: HabitFrequency.values.firstWhere(
              (e) => e.name.toUpperCase() == row[1].toString().toUpperCase(), // [1] is Frequency
              orElse: () => HabitFrequency.daily,
            ),
            targetDays: _parseDaysList(row[9].toString()), // [9] is sys_targetDays
            completedDates: _parseDatesList(row[5].toString()), // [5] is All Completed Dates
            createdAt: DateTime.tryParse(row[4].toString()) ?? DateTime.now(), // [4] is Created Date
          ),
        );
      } catch (e) {
        // If a row is corrupted, skip it and continue importing the rest
        log("Skipping corrupted row: $e");
      }
    }

    // D. Hand the finished list back to the Main Isolate!
    return importedHabits;
  }
  // --- Helper parsing methods for the Background Isolate ---

  static List<int> _parseDaysList(String data) {
    if (data.isEmpty) return [];
    // Parses the "1 | 2 | 3" format generated by your ExportService
    return data
        .split('|')
        .map((e) => int.tryParse(e.trim()))
        .where((e) => e != null)
        .cast<int>()
        .toList();
  }

  static List<DateTime> _parseDatesList(String data) {
    if (data.isEmpty) return [];
    return data
        .split('|')
        .map((e) => DateTime.tryParse(e.trim()))
        .where((e) => e != null)
        .cast<DateTime>()
        .toList();
  }
}
