import 'dart:developer';
import 'dart:io';
import 'dart:isolate';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
import '../../../features/habit_tracker/domain/entities/habit_entity.dart';

class ImportService {
  static Future<List<HabitEntity>?> importHabitsFromCSV() async {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );

    if (result == null || result.files.single.path == null) {
      return null;
    }

    // Isolate.run() automatically spins up a background thread, waits for it
    return await Isolate.run(
      () => _parseCSVInBackground(result.files.single.path!),
    );
  }

  static Future<List<HabitEntity>> _parseCSVInBackground(
    String filePath,
  ) async {
    // Read the heavy file from disk
    final file = File(filePath);
    final String csvString = await file.readAsString();

    // Parse the CSV string 
    List<List<dynamic>> csvTable = const CsvToListConverter().convert(
      csvString,
    );

    List<HabitEntity> importedHabits = [];

    // Convert CSV rows into Habit Entities
    for (int i = 1; i < csvTable.length; i++) {
      final row = csvTable[i];

      try {
        // Map the row columns back into a HabitEntity.
        importedHabits.add(
          HabitEntity(
            id: row[6].toString(),                
            title: row[0].toString(), 
            frequency: HabitFrequency.values.firstWhere(
              (e) => e.name.toUpperCase() == row[1].toString().toUpperCase(),
              orElse: () => HabitFrequency.daily,
            ),
            completedDates: _parseDatesList(row[5].toString()), 
            createdAt: DateTime.tryParse(row[4].toString()) ?? DateTime.now(),             
            iconCode: int.parse(row[7].toString()), 
            colorValue: int.parse(row[8].toString()),
            targetDays: _parseDaysList(row[9].toString()), 
          ),
        );
      } catch (e) {
        // If a row is corrupted, skip it and continue importing the rest
        log("Skipping corrupted row: $e");
      }
    }

    // Hand the finished list back to the Main Isolate!
    return importedHabits;
  }

  static List<int> _parseDaysList(String data) {
    if (data.isEmpty) return [];
    // Parses the "1 | 2 | 3" format generated by your ExportService
    return data
        .split('|')
        .map((e) => int.tryParse(e.trim()))
        .where((e) => e != null)
        .cast<int>()
        .toList();
  }

  static List<DateTime> _parseDatesList(String data) {
    if (data.isEmpty) return [];
    return data
        .split('|')
        .map((e) => DateTime.tryParse(e.trim()))
        .where((e) => e != null)
        .cast<DateTime>()
        .toList();
  }
}
