import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:habit_tracker_app_2026/core/services.dart';
import 'package:habit_tracker_app_2026/core/theme/app_theme.dart';
import 'package:habit_tracker_app_2026/core/theme/theme_provider.dart';
import 'package:habit_tracker_app_2026/features/habit_tracker/domain/usecases/delete_habit.dart';
import 'package:habit_tracker_app_2026/features/habit_tracker/domain/usecases/update_habit.dart';
import 'package:habit_tracker_app_2026/features/onboarding/presentation/pages/splash_screen.dart';
import 'package:hive_flutter/hive_flutter.dart';

// --- IMPORTS FROM YOUR FOLDER STRUCTURE ---
// 1. Data Layer
import 'package:habit_tracker_app_2026/features/habit_tracker/data/models/habit_model.dart';
import 'features/habit_tracker/data/datasources/local/habit_local_data_source.dart';
import 'features/habit_tracker/data/repositories/habit_repository_impl.dart';

// 2. Domain Layer
import 'features/habit_tracker/domain/repositories/i_habit_repository.dart';
import 'features/habit_tracker/domain/usecases/get_habits_for_date.dart';
import 'features/habit_tracker/domain/usecases/toggle_habit_completion.dart';
import 'features/habit_tracker/domain/usecases/create_habit.dart';

// 3. Presentation Layer
import 'features/habit_tracker/presentation/state_management/habit_provider.dart';

// -----------------------------------------------------------------------------
// DEPENDENCY INJECTION (WIRING THE LAYERS)
// -----------------------------------------------------------------------------

// 1. External (Database Box)
// We declare this as a provider, but we will override it in main() once the DB is open.
final habitBoxProvider = Provider<Box<HabitModel>>((ref) {
  throw UnimplementedError("Box not initialized");
});

// 2. Data Source (Depends on Box)
final localDataSourceProvider = Provider<HabitLocalDataSource>((ref) {
  final box = ref.watch(habitBoxProvider);
  return HabitLocalDataSourceImpl(habitBox: box);
});

// 3. Repository (Depends on Data Source)
final habitRepositoryProvider = Provider<IHabitRepository>((ref) {
  final dataSource = ref.watch(localDataSourceProvider);
  return HabitRepositoryImpl(localDataSource: dataSource);
});

// 4. Use Cases (Depend on Repository)
final getHabitsUseCaseProvider = Provider<GetHabitsForDate>((ref) {
  final repo = ref.watch(habitRepositoryProvider);
  return GetHabitsForDate(repo);
});

final toggleHabitUseCaseProvider = Provider<ToggleHabitCompletion>((ref) {
  final repo = ref.watch(habitRepositoryProvider);
  return ToggleHabitCompletion(repo);
});

final createHabitUseCaseProvider = Provider<CreateHabit>((ref) {
  final repo = ref.watch(habitRepositoryProvider);
  return CreateHabit(repo);
});

final updateHabitUseCaseProvider = Provider<UpdateHabit>((ref) {
  final repo = ref.watch(habitRepositoryProvider);
  return UpdateHabit(repo);
});

final deleteHabitUseCaseProvider = Provider<DeleteHabit>((ref) {
  final repo = ref.watch(habitRepositoryProvider);
  return DeleteHabit(repo);
});

// 5. State Management (The "Controller" for UI)
final habitNotifierProvider = StateNotifierProvider<HabitNotifier, HabitState>((ref) {
  // Inject the specific Use Cases needed for the UI
  return HabitNotifier(
    getHabitsUseCase: ref.watch(getHabitsUseCaseProvider),
    toggleUseCase: ref.watch(toggleHabitUseCaseProvider),
    createUseCase: ref.watch(createHabitUseCaseProvider),
    updateUseCase: ref.watch(updateHabitUseCaseProvider),
    deleteUseCase: ref.watch(deleteHabitUseCaseProvider)
  );
});


// -----------------------------------------------------------------------------
// MAIN ENTRY POINT
// -----------------------------------------------------------------------------

void main() async {
  // 1. Flutter Engine Setup
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Hive Initialization
  await Hive.initFlutter();

  await NotificationService().init();
  
  // Register Adapters (Generated by hive_generator)
  // Ensure you ran: flutter pub run build_runner build
  Hive.registerAdapter(HabitModelAdapter());
  // Hive.registerAdapter(HabitTypeAdapter()); // If you have an enum adapter

  // 3. Open Database Box
  final box = await Hive.openBox<HabitModel>('habits');
  await Hive.openBox('settings'); // For other app settings

  // 4. Run App with ProviderScope
  runApp(
    ProviderScope(
      // CRITICAL: We inject the OPENED box into the provider system here
      overrides: [
        habitBoxProvider.overrideWithValue(box),
      ],
      child:  MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
   const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeProvider);
    return MaterialApp(
      title: 'Growbit',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
      
      home:  const SplashScreen(),
    );
  }
}